sonar.projectKey=dvdmnc_sonar-samples
sonar.organization=david-menechi
sonar.projectName=TP SonarCloud
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
