sonar.projectKey=david-menechi_sonar-samples
sonar.organization=david-menechi
sonar.projectName=TP SonarCloud
sonar.sources=src
sonar.tests=test
sonar.exclusions=**/node_modules/**,**/coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
