sonar.projectKey=ClementRollin_sonar-samples
sonar.organization=clementrollin

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info,coverage/**/lcov.info