sonar.projectKey=BenjaminGleitz_sonar-samples
sonar.organization=benjamingleitz-1
sonar.projectName=TP SonarCloud
sonar.sources=src
sonar.tests=test
sonar.exclusions=**/node_modules/**,**/coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
