sonar.projectKey=sonar-samples-python
sonar.projectName=sonar-samples / python
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=.venv/**,**/__pycache__/**
sonar.host.url=http://localhost:9000
sonar.python.xunit.reportPath=test-results.xml
