sonar.projectKey=sonar-samples-angular
sonar.projectName=sonar-samples / angular
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,**/*.spec.ts,coverage/**
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://localhost:9000
