sonar.projectKey=sonar-samples-nodejs
sonar.projectName=sonar-samples / nodejs
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**
sonar.host.url=http://localhost:9000
sonar.testExecutionReportPaths=coverage/test-report.xml
